#!/bin/bash
# Bash script to apply NVIDIA GPU overclocking and power settings on session start
# To use overclocking, make sure your graphics card is allowing it first.
# Run: sudo nvidia-xconfig --cool-bits=31
# Then, restart the computer, or, end your session then log back in.
version='1.0.2'

error_nv_settings(){
echo "Couldn't find nvidia-settings! Exiting."
exit 1
}

set_gpu_clock(){
	 nvidia-settings -a "[gpu:$gpu]/GPUGraphicsClockOffset[$level]=$offset" >/dev/null 2>&1
}

set_mem_clock(){
	 nvidia-settings -a "[gpu:$gpu]/GPUMemoryTransferRateOffset[$level]=$offset" >/dev/null 2>&1
}

# Full path for autostart file
file_path="$HOME/.config/autostart/nvoc.desktop"

enable_autostart(){
mkdir -p $HOME/.config/autostart 2>/dev/null
echo "[Desktop Entry]" > $file_path
echo "Exec=nvoc" >> $file_path
echo "Icon=system-run" >> $file_path
echo "Name=nvoc" >> $file_path
echo "Terminal=False" >> $file_path
echo "Type=Application" >> $file_path
echo "Enabled nvoc auto-apply on login."
exit 0
}

disable_autostart(){
rm $file_path 2>/dev/null
echo "Disabled nvoc auto-apply on login."
exit 0
}

main(){
# Set GPU low-perf clocks
level=0
offset=$gpu_core_clock_offset_low
if (( $offset != 0 )); then
set_gpu_clock && echo "Applied core overclocking (low perf)"
fi
offset=$mem_clock_offset_low
if (( $offset != 0 )); then
set_mem_clock && echo "Applied memory overclocking (low perf)"
fi
# Set GPU medium-perf clocks
level=1
offset=$gpu_core_clock_offset_medium
if (( $offset != 0 )); then
set_gpu_clock && echo "Applied core overclocking (medium perf)"
fi
offset=$mem_clock_offset_medium
if (( $offset != 0 )); then
set_mem_clock && echo "Applied memory overclocking (medium perf)"
fi

# Set GPU high-perf clocks
# Some GPUs don't have the level 3 performance level,
# so we mash 2 and 3 together.
level=2 
offset=$gpu_core_clock_offset_high
if (( $offset != 0 )); then
set_gpu_clock && echo "Applied core overclocking (high perf-1)"
level=3
set_gpu_clock && echo "Applied core overclocking (high perf-2)"
else
echo "High performance core clocks remain unchanged."
echo "You might want to edit the configuration file at /etc/nvoc.d/gpu$gpu.conf."
fi

level=2          
offset=$mem_clock_offset_high
if (( $offset != 0 )); then
set_mem_clock && echo "Applied memory overclocking (high perf-1)"
level=3
set_mem_clock && echo "Applied memory overclocking (high perf-2)"
else
echo "High performance memory clocks remain unchanged."
echo "You might want to edit the configuration file at /etc/nvoc.d/gpu$gpu.conf."
fi
echo "All settings applied for GPU $gpu."
}

apply_all(){
# Detect nvidia-settings, and fail if it doesn't exist
command -v nvidia-settings >/dev/null 2>&1 || error_nv_settings

# Import settings and run
if [[ -d /etc/nvoc.d ]]; then
	for i in /etc/nvoc.d/*.conf; do
	source $i && main
	done
else
	echo "No configuration file found at /etc/nvoc.d/, exiting."
	echo "Try 'nvoc --help' for more information."
	exit 1
fi
}

print_help(){
echo "nvoc $version: the Nvidia overclocking offsets saver."
echo "Saves nvidia overclocking settings as easily editable configuration files in /etc/nvoc.d/"
echo "Automatically applies these settings on every desktop session start if prompted to. (try nvoc --enable-autostart)"
echo "Doesn't hang around as a background process - just applies and quits."
echo
echo "Usage: nvoc [options]"
echo "-a, --apply -> Apply overclocks in /etc/nvoc.d/"
echo "--enable-autostart -> Apply overclocks automatically on session start for this user"
echo "--disable-autostart -> Disable applying overclocks automatically on session start for this user"
echo "-h, -v, --help -> Shows this help message"
}

case $1 in
 	--enable-autostart) enable_autostart;;
	--disable-autostart) disable_autostart;;
	-h|-v|--help) print_help;;
	--apply|-a) apply_all;;
	*) echo "nvoc $version: the Nvidia overclocking offsets saver."
	   echo "Unknown command. Try 'nvoc --help' for more information."; exit 0 ;;
esac
echo "Done."


