#!/bin/bash
# Bash script to apply NVIDIA GPU overclocking and power settings on session start
# To use overclocking, make sure your graphics card is allowing it first.
# Run: sudo nvidia-xconfig --cool-bits=31
# Then, restart the computer, or, end your session then log back in.

error_nv_settings(){
echo "Couldn't find nvidia-settings! Exiting."
exit 1
}

# Detect nvidia-settings, and fail if it doesn't exist
command -v nvidia-settings >/dev/null 2>&1 || error_nv_settings

set_gpu_clock(){
	 nvidia-settings -a "[gpu:$gpu]/GPUGraphicsClockOffset[$level]=$offset" >/dev/null 2>&1
}

set_mem_clock(){
	 nvidia-settings -a "[gpu:$gpu]/GPUMemoryTransferRateOffset[$level]=$offset" >/dev/null 2>&1
}

main(){
# Set GPU low-perf clocks
level=0
offset=$gpu_core_clock_offset_low
if (( $offset != 0 )); then
set_gpu_clock && echo "Applied core overclocking (low perf)"
fi
offset=$mem_clock_offset_low
if (( $offset != 0 )); then
set_mem_clock && echo "Applied memory overclocking (low perf)"
fi
# Set GPU medium-perf clocks
level=1
offset=$gpu_core_clock_offset_medium
if (( $offset != 0 )); then
set_gpu_clock && echo "Applied core overclocking (medium perf)"
fi
offset=$mem_clock_offset_medium
if (( $offset != 0 )); then
set_mem_clock && echo "Applied memory overclocking (medium perf)"
fi

# Set GPU high-perf clocks
# Some GPUs don't have the level 3 performance level,
# so we mash 2 and 3 together.
level=2 
offset=$gpu_core_clock_offset_high
if (( $offset != 0 )); then
set_gpu_clock && echo "Applied core overclocking (high perf-1)"
level=3
set_gpu_clock && echo "Applied core overclocking (high perf-2)"
else
echo "High performance core clocks remain unchanged."
echo "You might want to edit the configuration file at /etc/nvoc.d/gpu$gpu.conf."
fi

level=2          
offset=$mem_clock_offset_high
if (( $offset != 0 )); then
set_mem_clock && echo "Applied memory overclocking (high perf-1)"
level=3
set_mem_clock && echo "Applied memory overclocking (high perf-2)"
else
echo "High performance memory clocks remain unchanged."
echo "You might want to edit the configuration file at /etc/nvoc.d/gpu$gpu.conf."
fi
echo "All settings applied for GPU $gpu."
}

# Import settings and run

if [[ -d /etc/nvoc.d ]]; then
	for i in /etc/nvoc.d/*.conf; do
	source $i && main
	done
else
	echo "No configuration file found at /etc/nvoc.d/, exiting."
	exit 1
fi

echo "Done."


